name: Publish Docker image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -f Dockerfile --tag ghcr.io/${{ github.repository }}:nightly 

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:nightly